# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on:
  pull_request:
    branches: [dev]
    paths:
      - '**.stories.tsx'
      - '.storybook/**'
      - 'package.json'
  push:
    branches: [dev]
    paths:
      - '**.stories.tsx'
      - '.storybook/**'

permissions:
  contents: read
  pull-requests: write

# List of jobs
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (PR)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout (push)
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Publish to Chromatic
        id: publish_chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build-storybook
          onlyChanged: true

      - name: comment PR
        uses: thollander/actions-comment-pull-request@v1
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: '🚀 **storybook**: ${{ steps.publish_chromatic.outputs.storybookUrl }}'
